name: peta_waktu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Packages - Untuk koneksi ke backend
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  # UI & Styling Packages
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  google_sign_in: ^6.1.0  
  flutter_facebook_auth: ^6.0.0
  image_picker: ^1.2.1
  cloudinary_public: ^0.23.1
  http: ^1.2.0
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
 